# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Installs packages from requirements.txt
RUN pip install flask

# Make port 5001 available outside this container
EXPOSE 5001

# Run app.py when the container launches
CMD ["python", "app.py"]